### ISSUE TITLE
Task 5. Broken indentions in loginform template 

### ISSUE THREAD

**Issue by SergioV85** [vposidailo/angular-mentee-program#5]
Incorrect indentions in the template. Please, see the attached image
![screen shot 2018-07-24 at 12 39 41](https://user-images.githubusercontent.com/8452421/43133363-cab4cb02-8f3e-11e8-97c2-c13199eb4d81.png)

**Comment by vposidailo** [comment]
Fixed.

**Comment by SergioV85** [comment]
Not fixed
![screen shot 2018-07-30 at 12 05 20](https://user-images.githubusercontent.com/8452421/43391403-e1ccf4ac-93f0-11e8-9df4-49373191e029.png)
